version: '3.4'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    container_name: app
    build:
      context: .
      dockerfile: dockerfile_celery
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/workspace
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - redis      
  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: dockerfile_celery
    command: celery -A tasks worker --pool=solo --loglevel=info
    volumes:
      - .:/workspace
    environment:
      - application_name="dev"
      - commitlog_directory="/tmp"
    depends_on:
      - redis
      - app
  celery_beat:
    container_name: celery_beat
    build:
      context: .
      dockerfile: dockerfile_celery
    command: celery -A tasks beat --pool=solo --loglevel=info
    volumes:
      - .:/workspace
    depends_on:
      - redis
      - app
  flower:
    container_name: flower
    build:
      context: .
      dockerfile: dockerfile_celery
    command: celery -A tasks flower --port=5555
    ports:
      - 5556:5555
    depends_on:
      - redis
      - app
      - celery_worker
      - celery_beat