AWSTemplateFormatVersion: 2010-09-09
Description: VaultDB Finance clouformation template
Metadata:
  Author: VaultDB.ai
  Url: https://www.vaultdb.ai/finance

Parameters:
  ApplicationName:
    Type: String
    AllowedPattern: "^[a-z][a-z0-9-]{0,48}[a-z0-9]$"
    Description: Enter the name of your application with no spaces.

Resources:
  FinanceLoadTickerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Tags:
        - Key: Purpose
          Value: "VaultDB"
        - Key: Project
          Value: !Ref ApplicationName
        - Key: createdBy
          Value: vaultdb.ai
      Description: Load All tickers to into VaultDB
      FunctionName: !Join ["", [!Ref ApplicationName, "-finance-ticker-load"]]
      Role:
        Fn::ImportValue: !Sub "${ApplicationName}-ExecuteRole"
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/vaultdb:finance"
      PackageType: Image
      ImageConfig:
        Command: 
          - finance_lambda.lambda_handler
      Architectures:
        - x86_64
      MemorySize: 256
      Timeout: 120
      Environment:
        Variables:
          application_name: !Sub "${ApplicationName}"
          AWS_STS_REGIONAL_ENDPOINTS: "regional"
          commitlog_directory: "/mnt/commitlog"
          HOME: "/mnt/commitlog"
          public_bucket:
            Fn::ImportValue: !Sub "${ApplicationName}-PublicBucket"
          data_store:
            Fn::ImportValue: !Sub "${ApplicationName}-DataBucket"
          user_pool_id:
            Fn::ImportValue: !Sub "${ApplicationName}-UserPool"
          user_pool_client_id:
            Fn::ImportValue: !Sub "${ApplicationName}-UserPoolClient"
          identity_pool_id:
            Fn::ImportValue: !Sub "${ApplicationName}-IdentityPool"
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub "${ApplicationName}-DataSecurityGroup"
        SubnetIds:
          - Fn::ImportValue: !Sub "${ApplicationName}-VPCPrivateSubnet"
      FileSystemConfigs:
        - Arn:
            Fn::ImportValue: !Sub "${ApplicationName}-EFSAccessPointResource"
          LocalMountPath: /mnt/commitlog

  ScheduleFinanceRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Scheduled data pull Runs"
      ScheduleExpression: "cron(0 17 * * ? *)" # Runs every day at 5 PM UTC
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt FinanceLoadTickerFunction.Arn
          Id: "UpdateKeysWeekly"
          Input: '{"RequestType":  "Refresh"}'

  PermissionForEventsToInvokeFinanceLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref FinanceLoadTickerFunction
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt FinanceLoadTickerFunction.Arn

Outputs:
  FinanceStepFunction:
    Description: VaultDB Fiancne Function
    Value: !Ref FinanceLoadTickerFunction
    Export:
      Name: !Sub ${ApplicationName}-FinanceLoadTickerFunction
