FROM public.ecr.aws/i2q7a2j7/vaultdb:lambda

WORKDIR /app

RUN pip3 install --upgrade pip
RUN pip3 install celery flower 
RUN pip3 install fastapi uvicorn
RUN pip3 install Redis

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

# Copy function code
COPY python/ /app/

# Install extensions
RUN python3 prepare.py

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

EXPOSE 8000

ENV PYTHONPATH="/app:$PATH"

ENTRYPOINT []