FROM public.ecr.aws/i2q7a2j7/vaultdb:lambda

# Add Tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

RUN mkdir -p ~/.vscode-server/extensions
RUN mkdir -p ~/.vscode-server-insiders/extensions

# Install utilitites
RUN dnf install -y tar gzip git

RUN pip3 install --upgrade pip
RUN pip3 install celery flower 
RUN pip3 install fastapi uvicorn
RUN pip3 install Redis
RUN pip3 install ipykernel

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV PYTHONPATH "${PYTHONPATH}:/workspace/python"

ENTRYPOINT ["/tini", "--"]