FROM public.ecr.aws/i2q7a2j7/vaultdb:lambda

# Add Tini
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

RUN mkdir -p ~/.vscode-server/extensions
RUN mkdir -p ~/.vscode-server-insiders/extensions

# Install utilitites
RUN dnf install -y tar gzip git

RUN pip3 install ipykernel

ENV PYTHONPATH "${PYTHONPATH}:/workspace/python"

ENTRYPOINT ["/tini", "--"]